version: "3.9"

services:

  db:
    image: postgres:16
    container_name: sr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_request
    ports:
      - "5432:5432"
    volumes:
      - sr_pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: sr_backend
    env_file:
      - .env.docker
    environment:
      DATABASE_URL_POSTGRES: ${DATABASE_URL_POSTGRES}
      API_KEY: ${API_KEY}
      ADMIN_BOOTSTRAP_KEY: ${ADMIN_BOOTSTRAP_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: sr_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  sr_pgdata:
